spring:
  h2:
    console:
      enabled: true
      path: '/db-console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/Wojciech Siwek/IdeaProjects/OpenProfWarehouse/opw-db.mv.db'
  jpa:
    hibernate:
      ddl-auto: update